### ISSUE TITLE
Cannot run linux app 1.7

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/hoverpad#24]
```
~/Downloads/hoverpad-linux-x64/hoverpad 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/mathieu/Downloads/hoverpad-linux-x64/resources/app/index.js'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/mathieu/Downloads/hoverpad-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Object.<anonymous> (/home/mathieu/Downloads/hoverpad-linux-x64/resources/electron.asar/browser/init.js:171:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**Comment by magopian** [comment]
Same issue on osx:
```Uncaught Exception:
Error: Cannot find module '/private/var/folders/vv/z388wrpn3vnbjzl850_l2hsw0000gn/T/AppTranslocation/9B23471F-1F45-4E3A-A4C9-C80F032CEE75/d/hoverpad.app/Contents/Resources/app/index.js'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/private/var/folders/vv/z388wrpn3vnbjzl850_l2hsw0000gn/T/AppTranslocation/9B23471F-1F45-4E3A-A4C9-C80F032CEE75/d/hoverpad.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Object.<anonymous> (/private/var/folders/vv/z388wrpn3vnbjzl850_l2hsw0000gn/T/AppTranslocation/9B23471F-1F45-4E3A-A4C9-C80F032CEE75/d/hoverpad.app/Contents/Resources/electron.asar/browser/init.js:171:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)```

**Comment by magopian** [comment]
It's because there's no `main` defined in the `package.json`, I'll update it, and re-release the 1.7 version

**Comment by magopian** [comment]
The [updated packages](https://github.com/mozilla-services/hoverpad/releases/tag/1.7) should now [do the trick](https://github.com/mozilla-services/hoverpad/commit/5e9f7bad1795eaa8bf6c9506eb7fae722cb8d4c1), please let me know if I can close this issue now @leplatrem !

**Comment by leplatrem** [comment]
Wooooorks! 

Thanks!
